# Generated by Django 3.0.7 on 2020-06-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_username',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
