# Generated by Django 3.0.7 on 2020-06-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_username',
            field=models.CharField(default='no username', max_length=30),
        ),
    ]
