# Generated by Django 3.0.7 on 2020-06-09 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200609_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_username',
        ),
    ]
