# Generated by Django 3.0.7 on 2020-06-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0002_project_project_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('bio', models.TextField()),
                ('profile_picture', models.ImageField(upload_to='api_pics')),
            ],
        ),
    ]
