# Generated by Django 3.0.7 on 2020-06-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0003_apiprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiprofile',
            name='profile_picture',
            field=models.ImageField(default='None', upload_to='api_pics'),
        ),
    ]
